### ISSUE TITLE
CI: Avoid fixed Quarkus version in CI runs

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#501]
## Description

https://github.com/graalvm/mandrel/pull/497 introduced fixed Quarkus versions in the CI workflows to work around failures due to [mandrel-integration-tests](https://github.com/Karm/mandrel-integration-tests/) failing to properly detect the Quarkus version from snapshot builds but introduces the following issues:

1. We need to manually update the workflow whenever a new Quarkus release for these versions comes out
2. We can no longer test backports to these branches before they get released

[Starting with 2.16 a new 2.16.999-SNAPSHOT version was adopted](https://github.com/quarkusio/quarkus/blob/13443aecbccb0fc72880d0788fed5bc21b8faedb/pom.xml#L16), this kind of SNAPSHOT version scheme could help with mandrel-integration-tests as well.

## Blocked by

- [x] [Applying the equivalent](https://github.com/graalvm/mandrel/pull/497#issuecomment-1522001551) of https://github.com/quarkusio/quarkus/pull/30860 to Quarkus branch 2.13. 

## TODO

- [x] Revert https://github.com/graalvm/mandrel/pull/497
- [x] Fix version detection in https://github.com/Karm/mandrel-integration-tests/

**Comment by zakkak** [comment]
> Revert https://github.com/graalvm/mandrel/pull/497

WIP in https://github.com/graalvm/mandrel/pull/673

> Fix version detection in https://github.com/Karm/mandrel-integration-tests/

WIP in https://github.com/Karm/mandrel-integration-tests/pull/247

**Comment by zakkak** [comment]
Both https://github.com/graalvm/mandrel/pull/673 and https://github.com/Karm/mandrel-integration-tests/pull/247 are now merged.
